### ISSUE TITLE
Images are not loading

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/dev-portal#20]
## Describe the bug

Images are not loading 

![Screenshot 2021-02-26 at 6 09 06 PM](https://user-images.githubusercontent.com/17899454/109304212-be019b00-785d-11eb-83a1-a1e491d61df3.png)

**Comment by lott-ai** [comment]
We should consider moving images to our CDN (cdn.stoplight.io) rather than hosting them in our Git repositories. This would require us to update the image URLs in the docs articles too.
